name: ci
on: push
permissions:
  packages: write
env:
  VERSION: v0.6.0
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dndx/phantun
          ref: ${{ env.VERSION }}
      # masterにしかdocker/Dockerfileがないので、masterからコピーする
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: dndx/phantun
          ref: 792ee46ec443276b4ae665e8671f54842ca13d92 # master
          path: phantun-master
      - name: Copy Dockerfile
        run: |
          cp -r phantun-master/docker docker
          cat <<EOF >> docker/Dockerfile
          RUN apt-get update && apt-get install -y iptables tzdata iproute2
          EOF
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/phantun:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
